import numpy as np
a = np.zeros (10)
a. shape = (2 , 5)
print (a)
b = 3*np.ones((3, 5), dtype = np.int32)
c = np.ones((3, 5), dtype = np.int32)
print (b)
print ("\n\n\n\n")
x = np.array ([1, 2, 3, 4])
y = np.array ([5, 6, 7, 8])
print (x + y)
print (x * y)
print (x + 10)
print (x * 10)
print (x @ y)
x.shape = (2 ,2)
y.shape = (2, 2)
print (b + c)
c.shape = (5, 3)
print (b.dot(c))
print (x @ y)
print (x @ [1, 2])